### ISSUE TITLE
Install Instructions Fail

### ISSUE THREAD

**Issue by jlpoolen** [sirjaren/gentoo-overlay#4]
themis ring-daemon #  cat >/etc/layman/overlays/sirjaren.xml
	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE repositories SYSTEM "/dtd/repositories.dtd">
	<repositories xmlns="" version="1.0">
	<repo quality="experimental" status="unofficial">
	   <name>sirjaren</name>
	   <description>flac/audio related ebuilds</description>
	   <homepage>https://github.com/sirjaren/gentoo-overlay</homepage>
	   <owner>
	       <email>sirjaren@gmail.com</email>
	       <name>sirjaren</name>
	   </owner>
	   <source type="git">git://github.com/sirjaren/gentoo-overlay.git</source>
	   <source type="git">https://github.com/sirjaren/gentoo-overlay.git</source>
	   <feed>https://github.com/sirjaren/gentoo-overlay/commits/master.atom</feed>
	</repo>
	</repositories>
	themis ring-daemon # layman -a sirjaren

	 * Adding overlay,...
	 * Exception: Overlay "sirjaren" does not exist.

	 * CLI: Errors occurred processing action add
	 * Exception: Overlay "sirjaren" does not exist.

	themis ring-daemon #

**Comment by jlpoolen** [comment]
Here's my layman.cfg:

	themis ring-daemon # cat /etc/layman/layman.cfg 
	[MAIN]
	#-----------------------------------------------------------
	# Defines the directory where overlays should be installed

	storage   : /var/lib/layman

	#-----------------------------------------------------------
	# Remote overlay lists will be stored here
	# layman will append _md5(url).xml to each filename

	cache     : %(storage)s/cache

	#-----------------------------------------------------------
	# The list of locally installed overlays

	installed: %(storage)s/installed.xml

	# This has been renamed from the following
	# old name  : value use it for updating to new one above
	# local_list: %(storage)s/overlays.xml
	# either rename the overlays.xml file to installed.xml
	# or edit the value above to the current name of your
	# installed overlay(s) file.

	#-----------------------------------------------------------
	# Path to the make.conf file that should be modified by
	# layman

	make_conf : %(storage)s/make.conf

	#-----------------------------------------------------------
	# URLs of the remote lists of overlays (one per line) or
	# local overlay definitions
	#
	#overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml
	#            http://dev.gentoo.org/~wrobel/layman/global-overlays.xml
	#            http://mydomain.org/my-layman-list.xml
	#            file:///var/lib/layman/my-list.xml

	overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml

	#-----------------------------------------------------------
	# The directory to scan for xml overlay definition files to include
	# in the list of available overlays.  They are automatically added to the
	# "overlays" parameter above.  Use either method, but do not add the same
	# definition in both.
	#

	#overlay_defs : /etc/layman/overlays

	#-----------------------------------------------------------
	# Proxy support
	# If unset, layman will use the http_proxy environment variable.
	#
	#proxy  : http://[user:pass@]www.my-proxy.org:3128

	#-----------------------------------------------------------
	# Strict checking of overlay definitions
	#
	# The nocheck option is a bit confusing, for historical reasons.
	# Hopefully this description eases the double negation trouble:
	#
	# nocheck : yes
	# - Accepts complete overlay entries without warnings
	# - Lists overlays of type foo (say Git) even with no foo installed
	#
	# nocheck : no
	# - Checks overlay entries for missing description or contact
	#     information and issue warnings as needed
	# - Hides overlays of type foo (say Git) if foo not not installed
	#
	nocheck  : yes

	#-----------------------------------------------------------
	# Umask settings
	#
	# layman should usually work with a umask of 0022. You should
	# only change this setting if you are absolutely certain that
	# you know what you are doing.
	#
	#umask  : 0022

	#-----------------------------------------------------------
	# News reporting settings
	#
	# This is for when layman is adding/syncing overlays.
	# It is required  for GLEP 42.
	# Currently there are 3 possible values:
	#   portage, pkgcore, custom
	#
	# portage:  uses portage to report news only from overlay(s) in
	#           versions >=2.2.0_alpha72 or >=2.1.10.32
	#           or all repositories (including gentoo) for older portage versions.
	# pkgcore:  does not yet support glep 42, no news is reported
	# custom:   requires that you provide a suitable python function
	#           to 'custom_news_func' using the api's config.set_option()
	#           or define the python package to import it from in custom_news_pkg

	news_reporter: portage

	#-----------------------------------------------------------
	# News reporting custom function setting
	#
	# the pkg name that contains the layman_news_function()
	# for it to import and use.  It must be found in PYTHONPATH

	#custom_news_pkg :

	#-----------------------------------------------------------
	# Command overrides
	#
	# You can have commands point to either a binary at a different
	# location, e.g.
	#
	#   /home/you/local/bin/git
	#
	# or just the command, e.g.
	#
	#   git
	#
	# to use PATH-based resolution of the binary to call.
	#
	#bzr_command        : /usr/bin/bzr
	#cvs_command        : /usr/bin/cvs
	#darcs_command      : /usr/bin/darcs
	#git_command        : /usr/bin/git
	#mercurial_command  : /usr/bin/hg
	#rsync_command      : /usr/bin/rsync
	#svn_command        : /usr/bin/svn
	#tar_command        : /bin/tar
	#g-common_command   : /usr/bin/g-common


	#-----------------------------------------------------------
	# Command additional options
	#
	# These commnad options will be added to the above commands
	# when the overlay is added or synced.
	#
	#    note: there are some options hardcoded in the backend
	#          scripts already.  All VCS types listed here are
	#          for general consistency.  Options may not be available
	#          or recommended for all VCS types and/or add/sync operations.
	#          Any options defined here are deemed:
	#                "Use at your own risk"
	#          and are not supported.
	#
	#  eg:
	#     svn_addopts : --config-option=config:miscellany:use-commit-times=yes
	#

	#bzr_addopts :
	#bzr_syncopts :
	#cvs_addopts :
	#cvs_syncopts :
	#darcs_addopts :
	#darcs_syncopts :
	#git_addopts :
	#git_syncopts :
	#mercurial_addopts :
	#mercurial_syncopts :
	#rsync_syncopts :
	#svn_addopts :
	#svn_syncopts :
	#g-common_generateopts :
	#g-common_syncopts :


	#-----------------------------------------------------------
	# Per VCS Post Sync/Add hooks
	#
	#  The listed commands will be run after every add/sync operation.
	#  All on one line  If the repo path is needed, use a %cwd= in
	#  where you want the path substituted in.  It will be detected
	#  and replaced with the correct path.
	#
	#  eg: git_postsync : git-set-file-times
	#  eg: git_postsync : git-set-file-times %cwd=
	#  eg: git_postsync : git-set-file-times path=%cwd=
	#
	#bzr_postsync :
	#cvs_postsync :
	#darcs_postsync :
	#git_postsync :
	#mercurial_postsync :
	#rsync_postsync :
	#svn_postsync :
	#tar_postsync :
	#g-common_postsync :


	#-----------------------------------------------------------
	# Layman user info
	#
	#  The user name and email to use when adding new repos
	#
	#git_user  : layman
	#git_email : layman@localhost


	themis ring-daemon #

**Comment by jlpoolen** [comment]
In the alternative, I added to my layman.cfg above:

	overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml
	#
	# 10/13/2015 jlpoole: for Epson Scanner
	#
	https://raw.github.com/sirjaren/gentoo-overlay/master/sirjaren.xml

	#-----------------------------------------------------------

and then:

	themis ring-daemon # layman -a sirjaren

	 * Adding overlay,...
	 * Running Git... # ( cd /var/lib/layman  && /usr/bin/git clone git://github.com/sirjaren/gentoo-overlay.git /var/lib/layman/sirjaren )
	Cloning into '/var/lib/layman/sirjaren'...
	remote: Counting objects: 175, done.
	remote: Compressing objects: 100% (16/16), done.
	remote: Total 175 (delta 4), reused 0 (delta 0), pack-reused 159
	Receiving objects: 100% (175/175), 29.21 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (28/28), done.
	Checking connectivity... done.
	 * Running Git... # ( cd /var/lib/layman/sirjaren  && /usr/bin/git config user.name "layman" )
	 * Running Git... # ( cd /var/lib/layman/sirjaren  && /usr/bin/git config user.email "layman@localhost" )
	 * Successfully added overlay(s) sirjaren.

	themis ring-daemon # 

Although the alternative worked, I think the first suggestion for installation ought to be revised or removed?

**Comment by jlpoolen** [comment]
It's been over a year since I've used layman, but I never have had problems installing packages from an overlay.  I'm really running into a roadblock here.

	themis mediawiki_ext # layman -s ALL

	 * Fetching remote list,...
	 * Fetching new list... http://www.gentoo.org/proj/en/overlays/repositories.xml
	 * Last-modified: Wed, 14 Oct 2015 19:10:16 GMT
	 * Fetch Ok

	 * Syncing selected overlays,...
	 * Running Git... # ( cd /var/lib/layman/sirjaren  && /usr/bin/git pull )
	Already up-to-date.
	 * 
	 * Succeeded:
	 * ------
	 * Successfully synchronized overlay "sirjaren".
	 * 

	themis mediawiki_ext #

Following the instructions at https://wiki.gentoo.org/wiki/Project:Overlays/User_Guide

	themis mediawiki_ext # layman -a sirjaren

	 * Adding overlay,...
	 * Repository 'sirjaren' was already installed

	 * CLI: Errors occurred processing action add
	 * Repository 'sirjaren' was already installed

	themis mediawiki_ext # 

	themis mediawiki_ext # emerge -av media-gfx/epson-ds

	 * IMPORTANT: 5 news items need reading for repository 'gentoo'.
	 * Use eselect news read to view new items.


	These are the packages that would be merged, in order:

	Calculating dependencies... done!

	emerge: there are no ebuilds to satisfy "media-gfx/epson-ds".

	emerge: searching for similar names...
	emerge: Maybe you meant any of these: media-gfx/peps, media-gfx/apngdis, media-gfx/postr?
	themis mediawiki_ext # 

I also created a file: /etc/portage/package.keywords/epson-ds which has this single line:

     themis mediawiki_ext # cat /etc/portage/package.keywords/epson-ds 
     media-gfx/epson-ds *
     themis mediawiki_ext # 

My goal is to get my DS-70000 working with my Gentoo Laptop.  I have an issue pending in the utsushi project where the scanner cannot be reached.  A suggestion came up to try this projects network access feature, so I installed my network panel on the scanner and have been trying to install your software but seem to be running into a roadblock.  Can you provide me some suggestions or steps so I can see it in eix or emerge -s?

**Comment by jlpoolen** [comment]
I abandoned trying to use the overlay, and just installed your ebuild directly:
	themis portage # cd /usr/local/portage
	themis portage # ls
	metadata  profiles  www-apps
	themis portage # mkdir media-gfx
	themis portage # cd media-gfx/
	themis media-gfx # mkdir epson-ds
	themis media-gfx # cp /home/jlpoole/epson/epson-ds-3.13.0.ebuild epson-ds
	themis media-gfx # cd epson-ds/
	themis epson-ds # ls
	epson-ds-3.13.0.ebuild
	themis epson-ds # ebuild epson-ds-3.13.0.ebuild digest
	>>> Downloading 'https://github.com/utsushi/imagescan/archive/3.13.0.tar.gz'
	--2015-10-15 07:03:43--  https://github.com/utsushi/imagescan/archive/3.13.0.tar.gz
	Resolving github.com... 192.30.252.130
	Connecting to github.com|192.30.252.130|:443... connected.
	HTTP request sent, awaiting response... 302 Found
	Location: https://codeload.github.com/utsushi/imagescan/tar.gz/3.13.0 [following]
	--2015-10-15 07:03:43--  https://codeload.github.com/utsushi/imagescan/tar.gz/3.13.0
	Resolving codeload.github.com... 192.30.252.145
	Connecting to codeload.github.com|192.30.252.145|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: unspecified [application/x-gzip]
	Saving to: ‘/usr/portage/distfiles/epson-ds-3.13.0.tar.gz’

	/usr/portage/distfi     [       <=>            ]  11.80M  1.16MB/s   in 9.3s   

	2015-10-15 07:03:53 (1.26 MB/s) - ‘/usr/portage/distfiles/epson-ds-3.13.0.tar.gz’ saved [12374786]

	>>> Creating Manifest for /usr/local/portage/media-gfx/epson-ds
	themis epson-ds # eix-update
	Reading Portage settings ..
	Building database (/var/cache/eix/portage.eix) ..
	[0] 'gentoo' /usr/portage/ (cache: metadata-md5-or-flat)
	     Reading category 164|164 (100%) Finished             
	[1] 'LocalPerl' /usr/local/portage (cache: parse|ebuild*#metadata-md5#metadata-assign#assign)
	     Reading category 164|164 (100%) Finished     
	Applying masks ..
	Calculating hash tables ..
	Writing database file /var/cache/eix/portage.eix ..
	Database contains 18650 packages in 164 categories.
	themis epson-ds # eix epson
	* media-gfx/epson-ds [1]
	     Available versions:  ~*3.13.0 {gtk imagemagick jpeg +network nls openmp tiff udev}
	     Homepage:            https://github.com/utsushi/utsushi
	     Description:         SANE backend driver for Epson DS line of scanners

	* net-print/epson-inkjet-printer-escpr
	     Available versions:  ~1.4.4 ~1.5.2
	     Homepage:            http://www.epson.com/
	     Description:         Epson Inkjet Printer Driver (ESC/P-R)

	[1] "LocalPerl" /usr/local/portage

	Found 2 matches.
	themis epson-ds #

**Comment by sirjaren** [comment]
Hello jlpoolen,

I've updated the instructions on how to use `layman` to add unofficial *ebuilds* (with this commit: b1c3e539b2df5044a8859ecc475e250a4358d3bf).

Please look [here](https://github.com/sirjaren/gentoo-overlay) for instructions.

Let me know how it goes.
Thanks!

**Comment by jlpoolen** [comment]
Working on it.  
Note: the current supported version of Layman is 2.0.0-r1, you indicated 2.3.0 is required.

    themis jlpoole # eix layman -I
    [I] app-portage/layman
         Available versions:  2.0.0-r1 2.0.0-r3 ~2.1.0-r3 ~2.2.0-r7 ~2.3.0 **9999 {bazaar cvs darcs g-sorcery +git gpg mercurial squashfs subversion sync-plugin-portage test PYTHON_TARGETS="pypy python2_7 python3_3 python3_4"}
         Installed versions:  2.0.0-r3(02:53:21 PM 05/24/2015)(git -bazaar -cvs -darcs -mercurial -subversion -test PYTHON_TARGETS="python2_7 -pypy")
         Homepage:            http://layman.sourceforge.net
         Description:         Tool to manage Gentoo overlays

    themis jlpoole #

**Comment by sirjaren** [comment]
Ah yes.

`layman-updater` is available with `layman 2.3.0`.  You don't have to go the route I specified, instead, you can do it manually.  Just follow the same instructions, and minus the `layman-updater`.  Should be sufficient to grab the new overlay.

**Comment by jlpoolen** [comment]
Followed the revised installation steps and was successful in the instllation of ` media-gfx/epson-ds` and its dependency ` media-gfx/epson-ds-plugins`.  I had to allow Layman 2.3.0 to be installed by adding a file "layman" under `/etc/portage/package.accept_keywords`

     themis utsushi_jlp # cat /etc/portage/package.accept_keywords/layman
     #
     # 10/18/2015 2.3.0+ required by https://github.com/sirjaren/gentoo-overlay
     #
     >=app-portage/layman-2.3.0
     themis utsushi_jlp #

**Comment by jlpoolen** [comment]
Thank you!
