### ISSUE TITLE
Emerge (rebuild) fails

### ISSUE THREAD

**Issue by jlpoolen** [sirjaren/gentoo-overlay#7]
I updated my system and on the rebuild, media-gfx/epson-ds-3.13.0::sirjaren failed (compile phase)

[media-gfx:epson-ds-3.13.0:20160426-132104_log.txt](https://github.com/sirjaren/gentoo-overlay/files/236711/media-gfx.epson-ds-3.13.0.20160426-132104_log.txt)
Here's the emerge -pqv:

> themis portage # emerge -pqv '=media-gfx/epson-ds-3.13.0::sirjaren'
> [ebuild   R   ] media-gfx/epson-ds-3.13.0  USE="jpeg network nls openmp tiff udev -gtk -imagemagick"
> - IMPORTANT: 1 news items need reading for repository 'gentoo'.
> - Use eselect news read to view new items.
> 
> themis portage #
> 
> [build_log.txt](https://github.com/sirjaren/gentoo-overlay/files/236717/build_log.txt)

Here's the emerge --info

> themis portage # emerge --info '=media-gfx/epson-ds-3.13.0::sirjaren'
> # Portage 2.2.26 (python 2.7.10-final-0, default/linux/amd64/13.0, gcc-4.9.3, glibc-2.22-r4, 4.1.12-gentoo x86_64)
> 
> ```
>                      System Settings
> ```
> # 
> 
> System uname: Linux-4.1.12-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_M_460_@_2.53GHz-with-gentoo-2.2
> KiB Mem:     5893524 total,   1785648 free
> KiB Swap:     524284 total,    512848 free
> Timestamp of repository gentoo: Mon, 25 Apr 2016 13:30:01 +0000
> sh bash 4.3_p42-r1
> ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
> ccache version 3.2.4 [disabled]
> app-shells/bash:          4.3_p42-r1::gentoo
> dev-java/java-config:     2.2.0-r3::gentoo
> dev-lang/perl:            5.20.2::gentoo
> dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
> dev-util/ccache:          3.2.4::gentoo
> dev-util/cmake:           3.3.1-r1::gentoo
> dev-util/pkgconfig:       0.28-r2::gentoo
> sys-apps/baselayout:      2.2::gentoo
> sys-apps/openrc:          0.19.1::gentoo
> sys-apps/sandbox:         2.10-r1::gentoo
> sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
> sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
> sys-devel/binutils:       2.25.1-r1::gentoo
> sys-devel/gcc:            4.9.3::gentoo
> sys-devel/gcc-config:     1.7.3::gentoo
> sys-devel/libtool:        2.4.6::gentoo
> sys-devel/make:           4.1-r1::gentoo
> sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
> sys-libs/glibc:           2.22-r4::gentoo
> Repositories:
> 
> gentoo
>     location: /usr/portage
>     sync-type: rsync
>     sync-uri: rsync://rsync.gentoo.org/gentoo-portage
>     priority: -1000
> 
> LocalPerl
>     location: /usr/local/portage
>     masters: gentoo
> 
> sirjaren
>     location: /var/lib/layman/sirjaren
>     masters: gentoo
>     priority: 50
> 
> ACCEPT_KEYWORDS="amd64"
> ACCEPT_LICENSE="\* -@EULA"
> CBUILD="x86_64-pc-linux-gnu"
> CFLAGS="-march=native -O2 -pipe"
> CHOST="x86_64-pc-linux-gnu"
> CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /var/lib/hsqldb"
> CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
> CXXFLAGS="-march=native -O2 -pipe"
> DISTDIR="/usr/portage/distfiles"
> FCFLAGS="-O2 -pipe"
> FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
> FFLAGS="-O2 -pipe"
> GENTOO_MIRRORS="http://gentoo.mirrors.hoobly.com/"
> LANG="en_US.utf8"
> LDFLAGS="-Wl,-O1 -Wl,--as-needed"
> MAKEOPTS="-j5"
> PKGDIR="/usr/portage/packages"
> PORTAGE_CONFIGROOT="/"
> PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
> PORTAGE_TMPDIR="/var/tmp"
> USE="X acl alsa amd64 berkdb bzip2 cli cracklib crypt cxx djvu dri ffmpeg fortran gdbm iconv ipv6 jpeg lock midi mmx mmxext modules mp3 multilib ncurses nls nptl openmp pam pcre pdf png postgres qt3support qt4 qt5 readline seccomp session sse sse2 ssl startup-notification tcpd thunar tiff udev unicode vorbis wavpack xattr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="auth_digest actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_loc deflate dir disk_cache env expires ext_filter file_cache filter headers include info log log_config logio mem_cache mime mime_module mime_magic negotiation rewrite setenvif speling ssl status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev synaptics" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="intel" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
> Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON
> # 
> 
> ```
>                     Package Settings
> ```
> # 
> 
> media-gfx/epson-ds-3.13.0::sirjaren was built with the following:
> USE="jpeg network nls openmp tiff udev -gtk -imagemagick" ABI_X86="64"
> 
> themis portage #

**Comment by sirjaren** [comment]
Hi @jlpoolen,

Try this newer ebuild (media-gfx/utsushi):
https://github.com/sirjaren/gentoo-overlay/tree/master/media-gfx/utsushi

This is the preferred package I'll be supporting.  Even though it's a live ebuild, the git repository just grabs packages (and community fixes) from the imagescan repository.

Hopefully, this will build for you.  Give it a try and let me know.

**Comment by ethus3h** [comment]
(I'm getting this when the network USE flag is set on utsushi. Not a big deal since I don't need network scanning, but, anyway…)

**Comment by sirjaren** [comment]
`media-gfx/epson-ds` is no longer supported.  Please use `media-gfx/utsushi` as that is the ebuild I'll support going forward, which provides all the same features as `media-gfx/epson-ds`:

https://github.com/sirjaren/gentoo-overlay/tree/master/media-gfx/utsushi

Closing for now.
Please open a new issue if there are failures/bugs with the `media-gfx/utsushi` ebuild.
